spring:
  profiles:
    include: secret
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # 파일 한 개당 최대 용량 제한 (기본값: 1MB)
      max-request-size: 100MB   # 한 번의 요청(여러 파일 합계)당 최대 용량 제한 (기본값: 10MB)

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: vintic-mvp-bucket-123
    region:
      static: ap-northeast-2

openai:
  api:
    key: ${OPENAI_API_KEY}

logging:
  level:
    root: INFO
    com.vintic.backend: INFO